version: '3.7'
services:
  node:
    container_name: node_server
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.prod
    # image: nguyenvanhontk4/back_end_travel
    networks:
      - common
    environment:
      PORT: 6969
      MONGO_URI: "mongodb+srv://admin123:12345@atlascluster.opryj2k.mongodb.net/"
      SALT_ROUNDS: "kamenriderDECADE"
      JWT_SECRET: "this is jwt serect"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - common
  nginx: 
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
    networks:
      - common
    
networks:
  common: 